/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.63
 * Generated at: 2021-08-09 08:24:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/G:/project/eclipse_project/SpringMVC/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BoyaBlogSys/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/G:/project/eclipse_project/SpringMVC/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BoyaBlogSys/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1628409202528L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme()+"://"+request.getServerName()+":"
		+request.getServerPort()+path;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"utf-8\">\r\n");
      out.write("\t\t<meta name=\"renderer\" content=\"webkit|ie-comp|ie-stand\">\r\n");
      out.write("\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no\" />\r\n");
      out.write("\t\t<meta http-equiv=\"Cache-Control\" content=\"no-siteapp\" />\r\n");
      out.write("\t\t<link rel=\"Bookmark\" href=\"");
      out.print(basePath);
      out.write("/resource/favicon.ico\" >\r\n");
      out.write("\t\t<link rel=\"Shortcut Icon\" href=\"");
      out.print(basePath);
      out.write("/resource/favicon.ico\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("/resource/static/h-ui/css/H-ui.min.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("/resource/static/h-ui.admin/css/H-ui.admin.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("/resource/lib/Hui-iconfont/1.0.8/iconfont.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("/resource/static/h-ui.admin/skin/default/skin.css\" id=\"skin\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("/resource/static/h-ui.admin/css/style.css\" />\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/resource/lib/jquery/1.9.1/jquery.min.js\"></script> \r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/resource/lib/layer/2.4/layer.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/resource/static/h-ui/js/H-ui.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/resource/static/h-ui.admin/js/H-ui.admin.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/resource/lib/jquery.contextmenu/jquery.contextmenu.r2.js\"></script>\r\n");
      out.write("\t\t<title>伯牙博客管理系统</title>\r\n");
      out.write("\t\t<meta name=\"keywords\" content=\"\">\r\n");
      out.write("\t\t<meta name=\"description\" content=\"\">\r\n");
      out.write("\t</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
 HttpSession s = request.getSession();  
      out.write("  \r\n");
      out.write("\t<header class=\"navbar-wrapper\">\r\n");
      out.write("\t\t<div class=\"navbar navbar-fixed-top\">\r\n");
      out.write("\t\t\t<div class=\"container-fluid cl\">\r\n");
      out.write("\t\t\t\t<span class=\"logo navbar-logo f-l mr-10 hidden-xs\">伯牙博客管理系统</span>\r\n");
      out.write("\t\t\t\t<a aria-hidden=\"false\" class=\"nav-toggle Hui-iconfont visible-xs\" href=\"javascript:;\">&#xe667;</a>\r\n");
      out.write("\t\t\t\t<nav id=\"Hui-userbar\" class=\"nav navbar-nav navbar-userbar hidden-xs\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"cl\">\r\n");
      out.write("\t\t\t\t\t\t<li>超级管理员</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropDown dropDown_hover\">\r\n");
      out.write("\t\t\t\t\t\t\t");
 if(s.getAttribute("supername")==null) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"dropDown_A\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t未登录<i class=\"Hui-iconfont\">&#xe6d5;</i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t    ");
 }else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t        <a href=\"#\" class=\"dropDown_A\">\r\n");
      out.write("\t\t\t\t\t\t        \t");
      out.print(session.getAttribute("supername"));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t        \t<i class=\"Hui-iconfont\">&#xe6d5;</i>\r\n");
      out.write("\t\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t\t\t     ");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropDown-menu menu radius box-shadow\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
 if(s.getAttribute("supername")==null) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"");
      out.print(basePath);
      out.write("/admin/login\">登录</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t        \t");
 }else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t       \t\t\t<li>\r\n");
      out.write("\t\t\t\t\t       \t\t\t\t<a href=\"");
      out.print(basePath);
      out.write("/admin/adminReset\">退出</a>\r\n");
      out.write("\t\t\t\t\t       \t\t\t</li>\r\n");
      out.write("\t\t\t\t\t        \t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t    </ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li id=\"Hui-skin\" class=\"dropDown right dropDown_hover\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"dropDown_A\" title=\"换肤\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"Hui-iconfont\" style=\"font-size:18px\">&#xe62a;</i>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropDown-menu menu radius box-shadow\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript:;\" data-val=\"default\" title=\"默认（黑色）\">默认（黑色）</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript:;\" data-val=\"blue\" title=\"蓝色\">蓝色</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript:;\" data-val=\"green\" title=\"绿色\">绿色</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript:;\" data-val=\"red\" title=\"红色\">红色</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript:;\" data-val=\"yellow\" title=\"黄色\">黄色</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript:;\" data-val=\"orange\" title=\"橙色\">橙色</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<aside class=\"Hui-aside\">\r\n");
      out.write("\t\t<div class=\"menu_dropdown bk_2\">\r\n");
      out.write("\t\t\t<dl id=\"menu-article\">\r\n");
      out.write("\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t<i class=\"Hui-iconfont\">&#xe616;</i>\r\n");
      out.write("\t\t\t\t\t用户管理\r\n");
      out.write("\t\t\t\t\t<i class=\"Hui-iconfont menu_dropdown-arrow\">&#xe6d5;</i>\r\n");
      out.write("\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a data-href=\"");
      out.print(basePath);
      out.write("/user/queryuse\" data-title=\"用户管理\" href=\"javascript:void(0)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t用户管理\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t\t<dl id=\"menu-picture\">\r\n");
      out.write("\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t<i class=\"Hui-iconfont\">&#xe613;</i>\r\n");
      out.write("\t\t\t\t\t文章管理\r\n");
      out.write("\t\t\t\t\t<i class=\"Hui-iconfont menu_dropdown-arrow\">&#xe6d5;</i>\r\n");
      out.write("\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a data-href=\"");
      out.print(basePath);
      out.write("/article/articlemana\" data-title=\"文章管理\" href=\"javascript:void(0)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t文章管理\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t\t<dl id=\"menu-product\">\r\n");
      out.write("\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t<i class=\"Hui-iconfont\">&#xe620;</i>\r\n");
      out.write("\t\t\t\t\t分类管理\r\n");
      out.write("\t\t\t\t\t<i class=\"Hui-iconfont menu_dropdown-arrow\">&#xe6d5;</i>\r\n");
      out.write("\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a data-href=\"");
      out.print(basePath);
      out.write("/catelog/catelog_index\"  data-title=\"分类管理\" href=\"javascript:void(0)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t分类管理\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t\t<dl id=\"menu-comments\">\r\n");
      out.write("\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t<i class=\"Hui-iconfont\">&#xe622;</i>\r\n");
      out.write("\t\t\t\t\t评论管理\r\n");
      out.write("\t\t\t\t\t<i class=\"Hui-iconfont menu_dropdown-arrow\">&#xe6d5;</i>\r\n");
      out.write("\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a data-href=\"");
      out.print(basePath);
      out.write("/comment/comment_index\" data-title=\"评论管理\" href=\"javascript:void(0)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t评论管理\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t\t<dl id=\"menu-comments\">\r\n");
      out.write("\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t<i class=\"Hui-iconfont\">&#xe622;</i>\r\n");
      out.write("\t\t\t\t\t留言管理\r\n");
      out.write("\t\t\t\t\t<i class=\"Hui-iconfont menu_dropdown-arrow\">&#xe6d5;</i>\r\n");
      out.write("\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a data-href=\"");
      out.print(basePath);
      out.write("/message/message_index\" data-title=\"留言管理\" href=\"javascript:void(0)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t留言管理\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t\t<dl id=\"menu-comments\">\r\n");
      out.write("\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t<i class=\"Hui-iconfont\">&#xe622;</i>\r\n");
      out.write("\t\t\t\t\t公告管理\r\n");
      out.write("\t\t\t\t\t<i class=\"Hui-iconfont menu_dropdown-arrow\">&#xe6d5;</i>\r\n");
      out.write("\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a data-href=\"");
      out.print(basePath);
      out.write("/post/post_index\" data-title=\"公告管理\" href=\"javascript:void(0)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t公告管理\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t\t<dl id=\"menu-admin\">\r\n");
      out.write("\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t<i class=\"Hui-iconfont\">&#xe62d;</i>\r\n");
      out.write("\t\t\t\t\t管理员管理\r\n");
      out.write("\t\t\t\t\t<i class=\"Hui-iconfont menu_dropdown-arrow\">&#xe6d5;</i>\r\n");
      out.write("\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a data-href=\"");
      out.print(basePath);
      out.write("/admin/admin_index\" data-title=\"管理员管理\" href=\"javascript:void(0)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t管理员管理\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t\t<dl id=\"menu-tongji\">\r\n");
      out.write("\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t<i class=\"Hui-iconfont\">&#xe61a;</i>\r\n");
      out.write("\t\t\t\t\t点赞统计\r\n");
      out.write("\t\t\t\t\t<i class=\"Hui-iconfont menu_dropdown-arrow\">&#xe6d5;</i>\r\n");
      out.write("\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a data-href=\"");
      out.print(basePath);
      out.write("/zan/zan_index\" data-title=\"点赞统计\" href=\"javascript:void(0)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t点赞统计\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</aside>\r\n");
      out.write("\t<div class=\"dislpayArrow hidden-xs\">\r\n");
      out.write("\t\t<a class=\"pngfix\" href=\"javascript:void(0);\" onClick=\"displaynavbar(this)\"></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<section class=\"Hui-article-box\">\r\n");
      out.write("\t\t<div id=\"Hui-tabNav\" class=\"Hui-tabNav hidden-xs\">\r\n");
      out.write("\t\t\t<div class=\"Hui-tabNav-wp\">\r\n");
      out.write("\t\t\t\t<ul id=\"min_title_list\" class=\"acrossTab cl\">\r\n");
      out.write("\t\t\t\t\t<li class=\"active\">\r\n");
      out.write("\t\t\t\t\t\t<span title=\"我的桌面\">\r\n");
      out.write("\t\t\t\t\t\t\t我的桌面\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t<em></em>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"Hui-tabNav-more btn-group\">\r\n");
      out.write("\t\t\t\t<a id=\"js-tabNav-prev\" class=\"btn radius btn-default size-S\" href=\"javascript:;\">\r\n");
      out.write("\t\t\t\t\t<i class=\"Hui-iconfont\">&#xe6d4;</i>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<a id=\"js-tabNav-next\" class=\"btn radius btn-default size-S\" href=\"javascript:;\">\r\n");
      out.write("\t\t\t\t\t<i class=\"Hui-iconfont\">&#xe6d7;</i>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"iframe_box\" class=\"Hui-article\">\r\n");
      out.write("\t\t\t<div class=\"show_iframe\">\r\n");
      out.write("\t\t\t\t<div style=\"display:none\" class=\"loading\"></div>\r\n");
      out.write("\t\t\t\t<iframe scrolling=\"yes\" frameborder=\"0\" src=\"");
      out.print(basePath);
      out.write("/resource/html/welcome.jsp\"></iframe>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<div class=\"contextMenu\" id=\"Huiadminmenu\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li id=\"closethis\">关闭当前 </li>\r\n");
      out.write("\t\t\t<li id=\"closeall\">关闭全部 </li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
